name: Build and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Get latest image tag
      id: get_tag
      run: echo "::set-output name=TAG::v1.0.$((($(git tag --list 'v1.0.*' | cut -d '.' -f 3 | sort -n | tail -n 1) + 1)))"

    - name: Build and push Docker image
      run: |
        TAG=$TAG
        IMAGE_TAG=ghcr.io/${{ github.repository_owner }}/sun:$TAG
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG

    - name: Update version tag in workflow file
      run: sed -i "s/v1.0.0/${{ steps.get_tag.outputs.TAG }}/g" your-workflow-file.yml
