name: CI

on:
  push:
    branches: [test]

  workflow_dispatch:

env:
  POSTGRESQL_DB: wedding
  POSTGRESQL_USER: postgres
  POSTGRESQL_PASSWORD: mysecretpassword
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
  IMAGE_TAG: ${{ github.run_number }} # Utilisation du numéro d'exécution du workflow comme base d'incrémentation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        run: |

      - uses: actions/checkout@v3
      - name: Build and push
        run: |
          set +x
          docker login --username ulrich-sun --password ${{ secrets.GH_PAT }} ghcr.io
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/wedding:v${{ env.IMAGE_TAG }}  .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/wedding:v${{ env.IMAGE_TAG }}
