name: Docker Image Publish

on:
  push:
    branches: [ "dev" ]
    # Publier les tags semver en tant que releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "dev" ]

env:
  # Utiliser docker.io pour Docker Hub si vide
  REGISTRY: ghcr.io
  # github.repository sous la forme <compte>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # Cela est utilisé pour compléter le challenge d'identité
      # avec sigstore/fulcio lorsqu'il est exécuté en dehors des PR.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Installation de l'outil cosign sauf sur les PR
      # https://github.com/sigstore/cosign-installer
      # - name: Install cosign
      #   if: github.event_name != 'pull_request'
      #   uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
      #   with:
      #     cosign-release: 'v1.11.1'

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à un registre Docker sauf sur PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'push'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # Extraction des métadonnées (tags, labels) pour Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Construction et publication de l'image Docker avec Buildx (ne pas publier sur PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: . # Utilise le répertoire de travail actuel comme contexte
          push: ${{ github.event_name != 'push' }} # Ne pas publier sur PR
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
