name: Build and Push

on:
  push:
    branches:
      - "*"
    tags:
      - "v*.*.*"
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest tag
        id: get_tag
        uses: docker/metadata-action@v5
        with: 
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Build and push the image
        run: |
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/${{ github.repository_owner }}/hello-world-sun:${{ steps.meta.outputs.tags }} 
          docker push ghcr.io/${{ github.repository_owner }}/hello-world-sun:${{ steps.meta.outputs.tags }}
          