name: Build and Push Docker Image

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GH_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        IMAGE_TAG=v1.0.0
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${IMAGE_TAG} .
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}:${IMAGE_TAG}

        # Increment the version tag
        IFS='.' read -r major minor patch <<< $IMAGE_TAG
        patch=$((patch + 1))
        IMAGE_TAG="$major.$minor.$patch"
        echo "::set-env name=IMAGE_TAG::$IMAGE_TAG"

    - name: Update version tag in workflow file
      run: sed -i "s/v1.0.0/${{ env.IMAGE_TAG }}/g" your-workflow-file.yml
