name: Build and Push

on:
  push:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username ulrich-sun --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/ulrich-sun/hello-world-sun:${{ github.ref_name }} 
          docker push ghcr.io/ulrich-sun/hello-world-sun:${{ github.ref_name }} 
