name: Build and Push

on:
  push:
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get latest tag
        id: get_tag
        run: echo ::set-output name=TAG_VERSION::v1.0.0
      - name: Cache tag
        id: cache_tag
        uses: actions/cache@v2
        with:
          path: new_tag.txt
          key: tag-version-${{ runner.os }}
      - name: Build and push the image
        run: |
          docker login --username ulrich-sun --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . -t ghcr.io/ulrich-sun/hello-world-sun:${{ steps.get_tag.outputs.TAG_VERSION }} 
          docker push ghcr.io/ulrich-sun/hello-world-sun:${{ steps.get_tag.outputs.TAG_VERSION }}
          current_version=$(echo '${{ steps.get_tag.outputs.TAG_VERSION }}' | tr -d 'v.')
          IFS='.' read -r major minor patch <<< "$current_version"
          echo "$major.$minor.$((patch + 1))" > new_tag.txt
          if [ $((patch + 1)) -eq 10 ]; then
            echo "$major.$((minor + 1)).0" > new_tag.txt
          fi
          echo ::set-output name=TAG_VERSION::v$(cat new_tag.txt)
      - name: Cache updated tag
        id: cache_updated_tag
        uses: actions/cache@v2
        with:
          path: new_tag.txt
          key: updated-tag-version-${{ runner.os }}